2023-09-14 16:57:46,255 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Configure stats pid to 127143
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/.config/wandb/settings
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/settings
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_init.py:_log_setup():524] Logging user logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_165746-i3trrbn6/logs/debug.log
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_init.py:_log_setup():525] Logging internal logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_165746-i3trrbn6/logs/debug-internal.log
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f419abb5870>
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_init.py:init():564] calling init triggers
2023-09-14 16:57:46,256 INFO    MainThread:127143 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2023-09-14 16:57:46,257 INFO    MainThread:127143 [wandb_init.py:init():614] starting backend
2023-09-14 16:57:46,257 INFO    MainThread:127143 [wandb_init.py:init():618] setting up manager
2023-09-14 16:57:46,258 INFO    MainThread:127143 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-14 16:57:46,259 INFO    MainThread:127143 [wandb_init.py:init():624] backend started and connected
2023-09-14 16:57:46,262 INFO    MainThread:127143 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-09-14 16:57:46,262 INFO    MainThread:127143 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-09-14 16:57:46,262 INFO    MainThread:127143 [wandb_init.py:init():715] updated telemetry
2023-09-14 16:57:46,264 INFO    MainThread:127143 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-09-14 16:57:47,098 INFO    MainThread:127143 [wandb_run.py:_on_init():2220] communicating current version
2023-09-14 16:57:47,268 INFO    MainThread:127143 [wandb_run.py:_on_init():2229] got version response 
2023-09-14 16:57:47,268 INFO    MainThread:127143 [wandb_init.py:init():799] starting run threads in backend
2023-09-14 16:57:52,218 WARNING MsgRouterThr:127143 [router.py:message_loop():77] message_loop has been closed
2023-09-14 16:57:58,060 ERROR   MainThread:127143 [wandb_init.py:init():1183] transport failed
Traceback (most recent call last):
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 810, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Configure stats pid to 127143
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/.config/wandb/settings
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/settings
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_init.py:_log_setup():524] Logging user logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170354-4cqx2nvs/logs/debug.log
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_init.py:_log_setup():525] Logging internal logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170354-4cqx2nvs/logs/debug-internal.log
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_init.py:init():564] calling init triggers
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_init.py:init():614] starting backend
2023-09-14 17:03:54,013 INFO    MainThread:127143 [wandb_init.py:init():618] setting up manager
2023-09-14 17:03:54,222 ERROR   MainThread:127143 [wandb_init.py:init():1193] error
Traceback (most recent call last):
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-09-14 17:05:54,963 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Configure stats pid to 127143
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/.config/wandb/settings
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/settings
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_init.py:_log_setup():524] Logging user logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170554-3tgpxpn1/logs/debug.log
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_init.py:_log_setup():525] Logging internal logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170554-3tgpxpn1/logs/debug-internal.log
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_init.py:init():564] calling init triggers
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2023-09-14 17:05:54,964 INFO    MainThread:127143 [wandb_init.py:init():614] starting backend
2023-09-14 17:05:54,965 INFO    MainThread:127143 [wandb_init.py:init():618] setting up manager
2023-09-14 17:05:55,108 ERROR   MainThread:127143 [wandb_init.py:init():1193] error
Traceback (most recent call last):
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Configure stats pid to 127143
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/.config/wandb/settings
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/settings
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:_log_setup():524] Logging user logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170606-u0xuikae/logs/debug.log
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:_log_setup():525] Logging internal logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170606-u0xuikae/logs/debug-internal.log
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():564] calling init triggers
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():614] starting backend
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():618] setting up manager
2023-09-14 17:06:06,357 ERROR   MainThread:127143 [wandb_init.py:init():1193] error
Traceback (most recent call last):
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
